service:
  port: ":8081"
  cloud_inary_url: "cloudinary://xxxxx:xxxxxx-xxxxx"

database:
  data_source_name: "user=root password=mypassword dbname=upload_image host=localhost port=5432 sslmode=disable"
