version: '3.9'
services:
  db:
    image: postgres:17-alpine
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=root
    volumes:
      - C:/docker_data/postgres:/var/lib/postgresql/data